name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'microsoft'
          cache: 'maven'
      - name: "Run tests and package"
        run: "mvn clean package assembly:single"
      - name: "Codecov report"
        run: bash <(curl -s https://codecov.io/bash)

